name: autoupdate
on:
  push:
    branches:
      - 'master'
jobs:
  autoupdate:
    name: autoupdate
    runs-on: [ self-hosted, ceragon-prod-runner ]
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          ##PR_FILTER: "auto_merge"
          MERGE_MSG: "Branch was auto-updated because auto-merge is enabled"
          MERGE_CONFLICT_ACTION: "ignore"
          DRY_RUN: true
